alias: null
batch_size: 32
callbacks:
- !!python/object:pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
  _enable_version_counter: true
  _every_n_epochs: 1
  _every_n_train_steps: 0
  _fs: &id001 !!python/object/apply:fsspec.spec.make_instance
  - !!python/name:fsspec.implementations.local.LocalFileSystem ''
  - !!python/tuple []
  - {}
  _last_checkpoint_saved: ''
  _last_global_step_saved: 0
  _last_time_checked: null
  _save_on_train_epoch_end: null
  _train_time_interval: null
  auto_insert_metric_name: true
  best_k_models: {}
  best_model_path: ''
  best_model_score: null
  current_score: null
  dirpath: null
  filename: null
  kth_best_model_path: ''
  kth_value: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYDwAAADEwNTU1MzIxMzA1ODAxNnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADEw
      NTU1MzIxMzA1ODAxNnEBYS4BAAAAAAAAAAAAgH8=
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  last_model_path: ''
  mode: min
  monitor: valid_loss
  save_last: null
  save_top_k: 1
  save_weights_only: false
  verbose: false
context_size: null
dataloader_kwargs: null
decoder_hidden_size: 128
decoder_layers: 2
drop_last_loader: false
early_stop_patience_steps: 15
enable_checkpointing: true
encoder_bias: true
encoder_dropout: 0.2
encoder_hidden_size: 32
encoder_n_layers: 2
exclude_insample_y: false
futr_exog_list:
- hour
- dayofweek
- month
- is_weekend
h: 30
h_train: 1
hist_exog_list:
- "T [\xB0C]"
- StrGlo [W/m2]
- RainDur [min]
- Hr [%Hr]
inference_input_size: null
inference_windows_batch_size: 1024
input_size: 120
learning_rate: 0.001
logger: !!python/object:pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  _default_hp_metric: true
  _experiment: null
  _fs: *id001
  _kwargs: {}
  _log_graph: false
  _name: LSTM_Multi
  _prefix: ''
  _root_dir: nf_tensorboard_log
  _sub_dir: null
  _version: null
  hparams: {}
loss: !!python/object:neuralforecast.losses.pytorch.MAE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: {}
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: {}
  _non_persistent_buffers_set: !!set {}
  _parameters: {}
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
lr_scheduler: null
lr_scheduler_kwargs: null
max_steps: 43500
n_samples: 100
n_series: 1
num_lr_decays: 5
optimizer: null
optimizer_kwargs: null
random_seed: 42
recurrent: false
scaler_type: standard
start_padding_enabled: false
stat_exog_list: null
step_size: 1
val_check_steps: 87
valid_batch_size: null
valid_loss: null
windows_batch_size: 128
